### ISSUE TITLE
make schema accessible from the companion object of the annotated class

### ISSUE THREAD

**Issue by julianpeeters** [julianpeeters/avro-scala-macro-annotations#1]
If we just need to get the schema of an annotated class, currently we have to construct an object like `MyRecord(1).getSchema`.  It would be nice to be able to just say `MyRecord.getSchema` or `MyRecord.schema`

**Comment by vidma** [comment]
:+1:  very useful!

**Comment by julianpeeters** [comment]
Turns out this will also fix a bug that prevents annotated case classes from being easily used as avro records when the avros are read as a stream:

" When deserializing from a stream, the Avro reader expects the read-mark to point to the schema. If we use a GenericRecord reader to read in the schema first, the read-mark points to the records so the read-mark needs to be reset (and the stream needs to allow it).  
For some reason this does not seem to be an issue when reading from Files."

- Raj Kumar

Current workaround from Raj Kumar:

    def deserialize[R]( is: InputStream): Iterator[R] = {
        val bis = if( is.markSupported ) is
                  else new BufferedInputStream( is )
        bis.mark( MAX_SCHEMA_SIZE )
        val schema = new DataFileStream( bis, new GenericDatumReader[R]).getSchema
        bis.reset
        val dr = new SpecificDatumReader[R]( schema )
        val dfr= new DataFileStream[R]( bis, dr)
        dfr.iterator
      }

Again, the bug and the workaround will be obviated when SCHEMA$ is introduced as a field of the companion object of the avro record case class, a la:

    val schema = MyRecord.SCHEMA$
    def deserialize[R]( schema: Schema, is: InputStream): Iterator[R] = {
        val dr = new SpecificDatumReader[R]( schema )
        val dfr= new DataFileStream[R]( bis, dr)
        dfr.iterator
      }

**Comment by julianpeeters** [comment]
Fixed in version 0.7
