### ISSUE TITLE
Adding default values in the schema?

### ISSUE THREAD

**Issue by sutram** [julianpeeters/avro-scala-macro-annotations#14]
Hi,
Is adding default values supported for the @AvroRecord annotation? Even if I set a default values for fields within case classes, it doesn't show up as a default value. Given this partial JSON:

```json
 {"name": "platform_deviceid", "type": "string"}
 ```
It would be great if I set a default value for the case class field like this:

```scala 
var platform_deviceid: String = "" 
```
that turns into:

```json
 {"name": "platform_deviceid", "type": "string", "default": ""} 
```
Using default values is useful during schema evolution (for example, when deleting the field shown above in future iterations of the schema)

**Comment by julianpeeters** [comment]
Not supported yet, but I'd like to, so thanks for the impetus.

I hope to have time to add this feature this weekend.

**Comment by sutram** [comment]
Cool - thanks.

**Comment by julianpeeters** [comment]
not published yet, but progress in this branch: [default_values](https://github.com/julianpeeters/avro-scala-macro-annotations/tree/default_values)

**Comment by julianpeeters** [comment]
Default values now supported for Scala 2.11, published as version 0.8.0.

Support for Scala 2.10 to  follow.

**Comment by sutram** [comment]
Awesome, I'll test and report back.

**Comment by julianpeeters** [comment]
Support can be had for 2.10 by using release version 0.4.1, should be syncing with maven central in a couple hours.
