### ISSUE TITLE
Support for "map" type?

### ISSUE THREAD

**Issue by sutram** [julianpeeters/avro-scala-macro-annotations#16]
Is this something that you are planning to add?
Thanks.

**Comment by julianpeeters** [comment]
Yes, however the timeframe for completion is uncertain. Likely within one or two months. Pull requests welcome.

**Comment by sutram** [comment]
Ok, no problem. Can you point me to the area of code that I need to look at?

**Comment by julianpeeters** [comment]
Sure. If you'd like to take a look, I've made a [branch](https://github.com/julianpeeters/avro-scala-macro-annotations/tree/map_type) with a handful of Map tests and AvroRecord will need to be updated for them to pass.

Avro takes in a ClassDef, reads its set of fields, and emits a ClassDef with new members based on those fields.   Specifically, the methods `generateNewCtors`, `generateSchema `, `generateNewMethods ` need to know what to generate when they are passed a set of fields that contains a map.

For example, when AvroRecord tries to make zero-arg constructor, it needs a default value for each field, but currently doesn't know what default to use when the field is a Map.

**Comment by julianpeeters** [comment]
I'm going to start on this feature, so if by chance there has been any progress here, please share any scraps. :)

**Comment by sutram** [comment]
Unfortunately, I've been extra busy recently so I haven't done much. Sorry.

**Comment by julianpeeters** [comment]
No worries at all.

Maps are now supported for Scala 2.11, with release version 0.9.0.

Support for Maps in 2.10 will come as well.

**Comment by sutram** [comment]
This works great! Looking forward to the port to 2.10.

Thanks,
Sutram

**Comment by julianpeeters** [comment]
Good to hear. 

You can try with 2.10 by using release version 0.4.1, should be syncing with maven central in a couple hours.

**Comment by sutram** [comment]
I verified that the 2.10 version works as well!

**Comment by julianpeeters** [comment]
OK great, thanks for the report. Happy Avro-ing.
