### ISSUE TITLE
Type macro to Unit

### ISSUE THREAD

**Issue by mariussoutier** [julianpeeters/avro-scala-macro-annotations#19]
Is it possible to not return something from the macros? sbt console is full of `discarded non-Unit value [warn] @AvroRecord` messages.

**Comment by julianpeeters** [comment]
Ah, I should use -Ywarn-value-discard more often.

This is fixed in release:

 0.9.1 for Scala 2.11, 

 0.4.2 for Scala 2.10.

**Comment by mariussoutier** [comment]
Thanks!
