### ISSUE TITLE
AvroTypeProvider generated case class aren't specific records

### ISSUE THREAD

**Issue by mariussoutier** [julianpeeters/avro-scala-macro-annotations#21]
case classes that are augmented by `@AvroTypeProvider` should also implement `SpecificRecordBase` to use them with serialization frameworks.

**Comment by julianpeeters** [comment]
Add the `@AvroRecord` annotation to implement `SpecificRecordBase`: 

    @AvroTypeProvider("data/input.avro")
    @AvroRecord
    case class MyRecord()

The functions are separate because not every Avro serialization framework requires SpecificRecords, and thus some users prefer "clean" case classes with immutable vals instead of vars.

**Comment by mariussoutier** [comment]
Sorry my bad, I forgot that second annotation on one case class. I also had the problem that you have to use `@AvroTypeProvider` first and `@AvroRecord` second, otherwise it won't compile.
