### ISSUE TITLE
Error reading an array of schmas

### ISSUE THREAD

**Issue by aakoshh** [julianpeeters/avro-scala-macro-annotations#29]
In order to avoid repeat the definition of a record multiple and be able to reuse them across a schema I tried defining them like this:
```
[
{
    "type": "record",
    "name": "Bar",
    "fields": [ ]
},
{
    "type": "record",
    "name": "Foo",
    "fields": [
        {"name": "first", "type": "Bar"}
        {"name": "second", "type": "Bar"}
    ]
}
]
```

When I tried to use this with `@AvroTypeProvider` I got: 
` java.lang.RuntimeException: no record type found in the union from path/to/schema.avsc`

The problem is that https://github.com/julianpeeters/avro-scala-macro-annotations/blob/master/macros/src/main/scala/avro/scala/macro/annotations/provider/FileParser.scala#L26 should check if `x.getType == RECORD`, not `x` itself.

That issue aside what I wanted to suggest that instead of returning the first schema from the union that has a record type you could maybe return either all of them or at least the last one? That's because if I put `Bar` after `Foo` I get parse error as `Bar` is not recognised. But left as in the example, the parsed `Schema` object corresponding to `Foo` will contain multiple occurrences of `Bar` so the existing finding mechanisms should work if the last schema of the union was returned.

**Comment by julianpeeters** [comment]
Hi Akos, thanks for your comments. Your suggestion sounds good to me. If your fork is working for you and you have a test case, go ahead and send a pull request and I'll publish ASAP.
