### ISSUE TITLE
How to use it properly?

### ISSUE THREAD

**Issue by ziziermao** [julianpeeters/avro-scala-macro-annotations#34]
When I looked at the examples,  case class always not taking any explicit parameters.
But when I was trying to use it at my code,
```
@AvroTypeProvider("src/main/avro/outputs/myclass.avro")
@AvroRecord
case class MyClass()
```

`GCalendar(value1, value2)`
I got **too many arguments for method apply**

Did I miss something? Could anyone please help

**Comment by julianpeeters** [comment]
Hi @ziziermao, please re-read the readme for more examples and usage instructions. Then if you're still stuck, please share your annotated class definition so I can see what you might be doing wrong.
