### ISSUE TITLE
Efficient serialisation of avro annotated case-classes

### ISSUE THREAD

**Issue by vidma** [julianpeeters/avro-scala-macro-annotations#5]
it looks quite natural to use operate on the same case classes for simple data processing. The operations which need the objects to be serialized (e.g. groupby, shuffle in scalding/Spark) - currently with Chill+Kryo, this would incur huge overhead - some 1KB+ for every record just because of the `SCHEMA$` field

so what should be the preferred way to (de)serialise these records? 

of course simplest is to write a custom serializer for every data type :(, but it would be nice to have a generic helper to do so.

--

one possibility could be to use CaseClass.unapply and apply (which don't include  `SCHEMA$`), and then somehow feed this into Chill. something along these lines:
https://github.com/twitter/chill/blob/42da58580409885afda0f3139835d82329009ca2/chill-bijection/src/test/scala/com/twitter/chill/CustomSerializationSpec.scala#L45-L63
but I cant yet find how to make this less verbose, and simpler

--

one could try to use Chill-Avro serialization, but apparently it doesn't work with annotations:

```scala
// https://github.com/twitter/chill/blob/911de385658aa012121620add4889a364d408d2f/chill-avro/src/main/scala/com/twitter/chill/avro/AvroSerializer.scala
import com.twitter.chill.avro.AvroSerializer
import com.julianpeeters.avro.annotations.AvroRecord

@AvroRecord
case class Test(var test: List[String])

AvroSerializer.SpecificRecordBinarySerializer[Test]
```

> org.apache.avro.AvroRuntimeException: java.lang.IllegalAccessException: Class org.apache.avro.specific.SpecificData can not access a member of class Test with modifiers "private final"
  at org.apache.avro.specific.SpecificData.createSchema(SpecificData.java:250)
  at org.apache.avro.specific.SpecificData.getSchema(SpecificData.java:189)
  at org.apache.avro.specific.SpecificDatumWriter.<init>(SpecificDatumWriter.java:33)
  at com.twitter.bijection.avro.SpecificAvroCodecs$.toBinary(AvroCodecs.scala:106)
  at com.twitter.chill.avro.AvroSerializer$.SpecificRecordBinarySerializer(AvroSerializer.scala:37)
  ... 43 elided
Caused by: java.lang.IllegalAccessException: Class org.apache.avro.specific.SpecificData can not access a member of class Test with modifiers "private final"
  at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:109)
  at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:261)
  at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:253)
  at java.lang.reflect.Field.get(Field.java:376)
  at org.apache.avro.specific.SpecificData.createSchema(SpecificData.java:240)
  ... 47 more

**Comment by julianpeeters** [comment]
I'm open to ideas as well.

I had copied the Java implementation of SpecificRecord's `SCHEMA$` and `getSchema()`, but perhaps that was foolish since all Scala fields are `private final`. 

I removed the `SCHEMA$` field since nothing can access it anyways. Now `getSchema()` does the schema parsing itself. 

Does that help?

        "com.julianpeeters" % "avro-scala-macro-annotations_2.10" % "0.3-SNAPSHOT"

**Comment by vidma** [comment]
looks :ok: now. Would be good to have a 2.11 version published also.

checked that Kryo don't include the huge overhead anymore
https://gist.github.com/vidma/cefce783108ed3946b7c

didn't check Chill's `AvroSerializer` yet..

**Comment by julianpeeters** [comment]
Excellent. Thanks for the feedback @vidma. Will publish for 2.10 and 2.11
by tomorrow.

**Comment by julianpeeters** [comment]
`"com.julianpeeters" % "avro-scala-macro-annotations_2.10" % "0.3"`
and

` "com.julianpeeters" % "avro-scala-macro-annotations_2.11" % "0.3"`

up at sonatype now, should sync with maven soon.
