### ISSUE TITLE
Requirement of var for records

### ISSUE THREAD

**Issue by ahjohannessen** [julianpeeters/avro-scala-macro-annotations#7]
Is there any plan to eliminate the need to use var for records? I do not mind annotations or macro usage, but using vars for otherwise immutable data structures like events used for eventsourcing and such feels wrong :/

**Comment by julianpeeters** [comment]
I agree, but Avro requires it (or rather the components of the Specific API require that they be mutable).

An alternative would be th use a different "Avro runtime" that allow one to use case classes with immutable fields to represent avro records, such as [Scalavro](https://github.com/GenslerAppsPod/scalavro) (or if you're brave and you need to read and write actual avro datafiles then [salat-avro](https://github.com/julianpeeters/salat-avro)), but I haven't tried either on a cluster (cf Apache Avro that plays so nicely with Spark/Hadoop).

**Comment by ahjohannessen** [comment]
I might work around this by using shapeless Generic / LabelledGeneric or perhaps twitter's bijection together with chill.
