### ISSUE TITLE
What would it take to add a fixed field to this?

### ISSUE THREAD

**Issue by dispalt** [julianpeeters/avro-scala-macro-annotations#8]
I am guessing you'd want to create another macro, do some checking to make sure it has a single field (ByteBuffer or Array[Byte]) and inherit from SpecificFixed, and add a macro on to the class @FixedSize(num).

Any ideas how to do this? I am having a harder time with this macro stuff than I thought =(

**Comment by julianpeeters** [comment]
In interested in supporting the fixed data type, but I haven't used it
before.

I'm thinking maybe I'd rather keep the number of macros to a minimum,
modifying @avrorecord instead. Or maybe another macro is the cleanest way.

What you suggest is doable. If you wanted to try, I'd start by using
@avrorecord as a model for how to get the argument of the annotation, and
how to pattern match the annotated class def in and output a modified
version complete with SpecificFixed base class.

Let me bone up on fixed, maybe I'll have a solution towards the end of the
week.

Cheers,
Julian

**Comment by ddispaltro** [comment]
I have a version of it working but the code is all mangled. Ill try to post it soon.

**Comment by julianpeeters** [comment]
Great!
